# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YWMwMGRiNGM4YzljZDAwYWYxODYxM2Q3M2YwNWFmYjE4YTA3NGM0YzI0MWNlODNlMDIzZmZmYTkzYTUzMWNlMjkwMTRiNjFjOTE1OGVlOGY3NmE2ZDQ4OGMyNTA1ZjM4ODZlYzgyOTRjZmZlOTAwNjZlZGEyNWQ3MGJkMjQzZGQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
